### ISSUE TITLE
BUG: seed file, process.env.NODE_ENV = 'test', reference error 'after is not defined'

### ISSUE THREAD

**Issue by dhf-fullstack** [FullstackAcademy/boilermaker#160]
* What is the expected behavior?

Expected to be able to seed the test database without errors

* What is the actual behavior?

server/db/db.js
after('close database connection')
ReferenceError: after not defined

* What steps reproduce the behavior?

export NODE_ENV=test
npm run seed

**Comment by glebec** [comment]
@dhf-fullstack Why are you directly running the seed file in test mode?

It is expected / intended that NODE_ENV will only be `test` when _running the tests_ via `npm test`, which uses `mocha` to run the app. Mocha registers `after` as a global variable.

**Comment by dhf-fullstack** [comment]
I didn't rtfm :(

when we changed a model, I wanted to change my local -test database without running the test suite. It was not a needful thing to do.

**Comment by glebec** [comment]
Nevertheless, this gives me an idea to change the sniffing from environmental to capability-based.

```js
if (global.after) {
    after(...)
}
```
