### ISSUE TITLE
New syntax needed with "history"

### ISSUE THREAD

**Issue by AlexandraBeautyman** [FullstackAcademy/boilermaker#173]
I get these two browser errors:

Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.

warnAboutDeprecatedCJSRequire.js:17 Warning: Please use `require("history").createMemoryHistory` instead of `require("history/createMemoryHistory")`. Support for the latter will be removed in the next major release.

**Comment by fterdal** [comment]
Yep, users will see this deprecation warning, and it's quite confusing, cause the boilermaker code doesn't use CommonJS-style require, it uses ES6 import statements.

![Screen Shot 2019-05-21 at 1 12 51 PM](https://user-images.githubusercontent.com/1832043/58120769-887d4780-7bcb-11e9-9529-7aab1576b7ac.png)

I'll submit a quick PR to fix this. Thanks for making an issue!
