### ISSUE TITLE
switch to `findOrCreate`

### ISSUE THREAD

**Issue by glebec** [FullstackAcademy/boilermaker#99]
https://github.com/FullstackAcademy/boilermaker/blob/ad468c9d2c7996540ea9d268eb126c0c6992d3b6/server/auth/google.js#L38-L44

This could probably be a `findOrCreate` with search query & default params (in case of create). From Fellows who taught 1804!

![bitmoji](https://render.bitstrips.com/v2/cpanel/fbf70eb2-c012-465e-9c1e-7b092675dfd8-e367812d-a53c-4b98-ade7-f17832f9596e-v1.png?transparent=1&palette=1&width=246)

**Comment by collin** [comment]
Wow, this is the first time I've seen that github markdown feature! Amazing

**Comment by collin** [comment]
Also yes.

**Comment by glebec** [comment]
> Wow, this is the first time I've seen that github markdown feature! 

I actually didn't know you could include multiple lines until I saw your edits, so yay teamwork.
